### ISSUE TITLE
我尝试在win10 QT 5.14上运行他，在人机对战中，人一下完棋后程序就卡死

### ISSUE THREAD

**Issue by XYZliang** [maplefan/RicardoGoBang#1]

**Comment by maplefan** [comment]
> _No description provided._

emmm...我在mac上开发的这个程序，在Windows上使用MinGW编译的Release版确定有你这个问题，但是Debug版却没问题，在macOS上Release和Debug版都木有问题，暂时不知道应该怎么解决这个问题5555
